apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: custom-nginx
  name: custom-nginx
spec:
  containers:
  - image: kodekloud/webapp-color
    name: custom-nginx
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: "purple"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
